# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/buddy_pokemon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/buddy_pokemon.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#pogoprotos/data/buddy_pokemon.proto\x12\x0fpogoprotos.data\"Z\n\x0c\x42uddyPokemon\x12\x18\n\x10\x62uddy_pokemon_id\x18\x01 \x01(\x06\x12\x17\n\x0fstart_km_walked\x18\x02 \x01(\x01\x12\x17\n\x0flast_km_awarded\x18\x03 \x01(\x01\x62\x06proto3')
)




_BUDDYPOKEMON = _descriptor.Descriptor(
  name='BuddyPokemon',
  full_name='pogoprotos.data.BuddyPokemon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buddy_pokemon_id', full_name='pogoprotos.data.BuddyPokemon.buddy_pokemon_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_km_walked', full_name='pogoprotos.data.BuddyPokemon.start_km_walked', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_km_awarded', full_name='pogoprotos.data.BuddyPokemon.last_km_awarded', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['BuddyPokemon'] = _BUDDYPOKEMON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuddyPokemon = _reflection.GeneratedProtocolMessageType('BuddyPokemon', (_message.Message,), dict(
  DESCRIPTOR = _BUDDYPOKEMON,
  __module__ = 'pogoprotos.data.buddy_pokemon_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.BuddyPokemon)
  ))
_sym_db.RegisterMessage(BuddyPokemon)


# @@protoc_insertion_point(module_scope)
