# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/get_action_log_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/get_action_log_request.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,pogoprotos/data/get_action_log_request.proto\x12\x0fpogoprotos.data\"\x15\n\x13GetActionLogRequestb\x06proto3')
)




_GETACTIONLOGREQUEST = _descriptor.Descriptor(
  name='GetActionLogRequest',
  full_name='pogoprotos.data.GetActionLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['GetActionLogRequest'] = _GETACTIONLOGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetActionLogRequest = _reflection.GeneratedProtocolMessageType('GetActionLogRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETACTIONLOGREQUEST,
  __module__ = 'pogoprotos.data.get_action_log_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.GetActionLogRequest)
  ))
_sym_db.RegisterMessage(GetActionLogRequest)


# @@protoc_insertion_point(module_scope)
