# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/fitness/fitness_metrics_report_history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.fitness import fitness_metrics_pb2 as pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/fitness/fitness_metrics_report_history.proto',
  package='pogoprotos.data.fitness',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n<pogoprotos/data/fitness/fitness_metrics_report_history.proto\x12\x17pogoprotos.data.fitness\x1a-pogoprotos/data/fitness/fitness_metrics.proto\"\xb2\x02\n\x1b\x46itnessMetricsReportHistory\x12[\n\x0eweekly_history\x18\x01 \x03(\x0b\x32\x43.pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory\x12Z\n\rdaily_history\x18\x02 \x03(\x0b\x32\x43.pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory\x1aZ\n\x0eMetricsHistory\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x03\x12\x38\n\x07metrics\x18\x02 \x01(\x0b\x32\'.pogoprotos.data.fitness.FitnessMetricsb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2.DESCRIPTOR,])




_FITNESSMETRICSREPORTHISTORY_METRICSHISTORY = _descriptor.Descriptor(
  name='MetricsHistory',
  full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket', full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory.bucket', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory.metrics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=443,
)

_FITNESSMETRICSREPORTHISTORY = _descriptor.Descriptor(
  name='FitnessMetricsReportHistory',
  full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weekly_history', full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory.weekly_history', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='daily_history', full_name='pogoprotos.data.fitness.FitnessMetricsReportHistory.daily_history', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FITNESSMETRICSREPORTHISTORY_METRICSHISTORY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=443,
)

_FITNESSMETRICSREPORTHISTORY_METRICSHISTORY.fields_by_name['metrics'].message_type = pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2._FITNESSMETRICS
_FITNESSMETRICSREPORTHISTORY_METRICSHISTORY.containing_type = _FITNESSMETRICSREPORTHISTORY
_FITNESSMETRICSREPORTHISTORY.fields_by_name['weekly_history'].message_type = _FITNESSMETRICSREPORTHISTORY_METRICSHISTORY
_FITNESSMETRICSREPORTHISTORY.fields_by_name['daily_history'].message_type = _FITNESSMETRICSREPORTHISTORY_METRICSHISTORY
DESCRIPTOR.message_types_by_name['FitnessMetricsReportHistory'] = _FITNESSMETRICSREPORTHISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FitnessMetricsReportHistory = _reflection.GeneratedProtocolMessageType('FitnessMetricsReportHistory', (_message.Message,), dict(

  MetricsHistory = _reflection.GeneratedProtocolMessageType('MetricsHistory', (_message.Message,), dict(
    DESCRIPTOR = _FITNESSMETRICSREPORTHISTORY_METRICSHISTORY,
    __module__ = 'pogoprotos.data.fitness.fitness_metrics_report_history_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.fitness.FitnessMetricsReportHistory.MetricsHistory)
    ))
  ,
  DESCRIPTOR = _FITNESSMETRICSREPORTHISTORY,
  __module__ = 'pogoprotos.data.fitness.fitness_metrics_report_history_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.fitness.FitnessMetricsReportHistory)
  ))
_sym_db.RegisterMessage(FitnessMetricsReportHistory)
_sym_db.RegisterMessage(FitnessMetricsReportHistory.MetricsHistory)


# @@protoc_insertion_point(module_scope)
