# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/fitness/fitness_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.fitness import fitness_metrics_pb2 as pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/fitness/fitness_stats.proto',
  package='pogoprotos.data.fitness',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+pogoprotos/data/fitness/fitness_stats.proto\x12\x17pogoprotos.data.fitness\x1a-pogoprotos/data/fitness/fitness_metrics.proto\"\xeb\x01\n\x0c\x46itnessStats\x12%\n\x1dlast_accumulated_timestamp_ms\x18\x01 \x01(\x03\x12<\n\x0b\x61\x63\x63umulated\x18\x02 \x01(\x0b\x32\'.pogoprotos.data.fitness.FitnessMetrics\x12\x38\n\x07pending\x18\x03 \x01(\x0b\x32\'.pogoprotos.data.fitness.FitnessMetrics\x12\x1e\n\x16player_initial_walk_km\x18\x04 \x01(\x01\x12\x1c\n\x14player_total_walk_km\x18\x05 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2.DESCRIPTOR,])




_FITNESSSTATS = _descriptor.Descriptor(
  name='FitnessStats',
  full_name='pogoprotos.data.fitness.FitnessStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_accumulated_timestamp_ms', full_name='pogoprotos.data.fitness.FitnessStats.last_accumulated_timestamp_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accumulated', full_name='pogoprotos.data.fitness.FitnessStats.accumulated', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pending', full_name='pogoprotos.data.fitness.FitnessStats.pending', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_initial_walk_km', full_name='pogoprotos.data.fitness.FitnessStats.player_initial_walk_km', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_total_walk_km', full_name='pogoprotos.data.fitness.FitnessStats.player_total_walk_km', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=355,
)

_FITNESSSTATS.fields_by_name['accumulated'].message_type = pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2._FITNESSMETRICS
_FITNESSSTATS.fields_by_name['pending'].message_type = pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2._FITNESSMETRICS
DESCRIPTOR.message_types_by_name['FitnessStats'] = _FITNESSSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FitnessStats = _reflection.GeneratedProtocolMessageType('FitnessStats', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSSTATS,
  __module__ = 'pogoprotos.data.fitness.fitness_stats_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.fitness.FitnessStats)
  ))
_sym_db.RegisterMessage(FitnessStats)


# @@protoc_insertion_point(module_scope)
