# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/limited_purchase_sku_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/limited_purchase_sku_settings.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n>pogoprotos/settings/master/limited_purchase_sku_settings.proto\x12\x1apogoprotos.settings.master\"E\n\x1aLimitedPurchaseSkuSettings\x12\x16\n\x0epurchase_limit\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\x05\x62\x06proto3')
)




_LIMITEDPURCHASESKUSETTINGS = _descriptor.Descriptor(
  name='LimitedPurchaseSkuSettings',
  full_name='pogoprotos.settings.master.LimitedPurchaseSkuSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='purchase_limit', full_name='pogoprotos.settings.master.LimitedPurchaseSkuSettings.purchase_limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pogoprotos.settings.master.LimitedPurchaseSkuSettings.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['LimitedPurchaseSkuSettings'] = _LIMITEDPURCHASESKUSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LimitedPurchaseSkuSettings = _reflection.GeneratedProtocolMessageType('LimitedPurchaseSkuSettings', (_message.Message,), dict(
  DESCRIPTOR = _LIMITEDPURCHASESKUSETTINGS,
  __module__ = 'pogoprotos.settings.master.limited_purchase_sku_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.LimitedPurchaseSkuSettings)
  ))
_sym_db.RegisterMessage(LimitedPurchaseSkuSettings)


# @@protoc_insertion_point(module_scope)
