# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/incident_leader_string_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/incident_leader_string_types.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3pogoprotos/enums/incident_leader_string_types.proto\x12\x10pogoprotos.enums*v\n\x19IncidentLeaderStringTypes\x12\x1b\n\x17ONBOARDING_INTRODUCTION\x10\x00\x12\x18\n\x14ONBOARDING_ENCOUNTER\x10\x01\x12\x15\n\x11ONBOARDING_SHADOW\x10\x02\x12\x0b\n\x07INSPIRE\x10\x03\x62\x06proto3')
)

_INCIDENTLEADERSTRINGTYPES = _descriptor.EnumDescriptor(
  name='IncidentLeaderStringTypes',
  full_name='pogoprotos.enums.IncidentLeaderStringTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONBOARDING_INTRODUCTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONBOARDING_ENCOUNTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONBOARDING_SHADOW', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSPIRE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=73,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_INCIDENTLEADERSTRINGTYPES)

IncidentLeaderStringTypes = enum_type_wrapper.EnumTypeWrapper(_INCIDENTLEADERSTRINGTYPES)
ONBOARDING_INTRODUCTION = 0
ONBOARDING_ENCOUNTER = 1
ONBOARDING_SHADOW = 2
INSPIRE = 3


DESCRIPTOR.enum_types_by_name['IncidentLeaderStringTypes'] = _INCIDENTLEADERSTRINGTYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
