# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/fort/sponsored_details.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/map/fort/sponsored_details.proto',
  package='pogoprotos.map.fort',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+pogoprotos/map/fort/sponsored_details.proto\x12\x13pogoprotos.map.fort\"\x84\x02\n\x10SponsoredDetails\x12\x17\n\x0fpromo_image_url\x18\x01 \x03(\t\x12\x19\n\x11promo_description\x18\x02 \x03(\t\x12\x1b\n\x13\x63\x61ll_to_action_link\x18\x03 \x01(\t\x12_\n\x19promo_button_message_type\x18\x04 \x01(\x0e\x32<.pogoprotos.map.fort.SponsoredDetails.PromoButtonMessageType\">\n\x16PromoButtonMessageType\x12\t\n\x05UNSET\x10\x00\x12\x0e\n\nLEARN_MORE\x10\x01\x12\t\n\x05OFFER\x10\x02\x62\x06proto3')
)



_SPONSOREDDETAILS_PROMOBUTTONMESSAGETYPE = _descriptor.EnumDescriptor(
  name='PromoButtonMessageType',
  full_name='pogoprotos.map.fort.SponsoredDetails.PromoButtonMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEARN_MORE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFFER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=267,
  serialized_end=329,
)
_sym_db.RegisterEnumDescriptor(_SPONSOREDDETAILS_PROMOBUTTONMESSAGETYPE)


_SPONSOREDDETAILS = _descriptor.Descriptor(
  name='SponsoredDetails',
  full_name='pogoprotos.map.fort.SponsoredDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='promo_image_url', full_name='pogoprotos.map.fort.SponsoredDetails.promo_image_url', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='promo_description', full_name='pogoprotos.map.fort.SponsoredDetails.promo_description', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_to_action_link', full_name='pogoprotos.map.fort.SponsoredDetails.call_to_action_link', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='promo_button_message_type', full_name='pogoprotos.map.fort.SponsoredDetails.promo_button_message_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPONSOREDDETAILS_PROMOBUTTONMESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=329,
)

_SPONSOREDDETAILS.fields_by_name['promo_button_message_type'].enum_type = _SPONSOREDDETAILS_PROMOBUTTONMESSAGETYPE
_SPONSOREDDETAILS_PROMOBUTTONMESSAGETYPE.containing_type = _SPONSOREDDETAILS
DESCRIPTOR.message_types_by_name['SponsoredDetails'] = _SPONSOREDDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SponsoredDetails = _reflection.GeneratedProtocolMessageType('SponsoredDetails', (_message.Message,), dict(
  DESCRIPTOR = _SPONSOREDDETAILS,
  __module__ = 'pogoprotos.map.fort.sponsored_details_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.map.fort.SponsoredDetails)
  ))
_sym_db.RegisterMessage(SponsoredDetails)


# @@protoc_insertion_point(module_scope)
