# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/titan/messages/submit_poi_location_update_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/titan/messages/submit_poi_location_update_message.proto',
  package='pogoprotos.networking.titan.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nMpogoprotos/networking/titan/messages/submit_poi_location_update_message.proto\x12$pogoprotos.networking.titan.messages\"\xcc\x01\n\x1eSubmitPoiLocationUpdateMessage\x12\x0e\n\x06poi_id\x18\x01 \x01(\t\x12\x61\n\x08location\x18\x02 \x01(\x0b\x32O.pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.LocationE6\x1a\x37\n\nLocationE6\x12\x13\n\x0blatitude_e6\x18\x01 \x01(\x05\x12\x14\n\x0clongitude_e6\x18\x02 \x01(\x05\x62\x06proto3')
)




_SUBMITPOILOCATIONUPDATEMESSAGE_LOCATIONE6 = _descriptor.Descriptor(
  name='LocationE6',
  full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.LocationE6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude_e6', full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.LocationE6.latitude_e6', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude_e6', full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.LocationE6.longitude_e6', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=324,
)

_SUBMITPOILOCATIONUPDATEMESSAGE = _descriptor.Descriptor(
  name='SubmitPoiLocationUpdateMessage',
  full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poi_id', full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.poi_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SUBMITPOILOCATIONUPDATEMESSAGE_LOCATIONE6, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=324,
)

_SUBMITPOILOCATIONUPDATEMESSAGE_LOCATIONE6.containing_type = _SUBMITPOILOCATIONUPDATEMESSAGE
_SUBMITPOILOCATIONUPDATEMESSAGE.fields_by_name['location'].message_type = _SUBMITPOILOCATIONUPDATEMESSAGE_LOCATIONE6
DESCRIPTOR.message_types_by_name['SubmitPoiLocationUpdateMessage'] = _SUBMITPOILOCATIONUPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitPoiLocationUpdateMessage = _reflection.GeneratedProtocolMessageType('SubmitPoiLocationUpdateMessage', (_message.Message,), dict(

  LocationE6 = _reflection.GeneratedProtocolMessageType('LocationE6', (_message.Message,), dict(
    DESCRIPTOR = _SUBMITPOILOCATIONUPDATEMESSAGE_LOCATIONE6,
    __module__ = 'pogoprotos.networking.titan.messages.submit_poi_location_update_message_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage.LocationE6)
    ))
  ,
  DESCRIPTOR = _SUBMITPOILOCATIONUPDATEMESSAGE,
  __module__ = 'pogoprotos.networking.titan.messages.submit_poi_location_update_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.titan.messages.SubmitPoiLocationUpdateMessage)
  ))
_sym_db.RegisterMessage(SubmitPoiLocationUpdateMessage)
_sym_db.RegisterMessage(SubmitPoiLocationUpdateMessage.LocationE6)


# @@protoc_insertion_point(module_scope)
