# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/quests/quest_precondition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import badge_type_pb2 as pogoprotos_dot_enums_dot_badge__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/quests/quest_precondition.proto',
  package='pogoprotos.data.quests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/pogoprotos/data/quests/quest_precondition.proto\x12\x16pogoprotos.data.quests\x1a!pogoprotos/enums/badge_type.proto\"\xd7\x07\n\x11QuestPrecondition\x12M\n\x04type\x18\x01 \x01(\x0e\x32?.pogoprotos.data.quests.QuestPrecondition.QuestPreconditionType\x12\x1b\n\x11quest_template_id\x18\x02 \x01(\tH\x00\x12@\n\x05level\x18\x03 \x01(\x0b\x32/.pogoprotos.data.quests.QuestPrecondition.LevelH\x00\x12@\n\x05medal\x18\x04 \x01(\x0b\x32/.pogoprotos.data.quests.QuestPrecondition.MedalH\x00\x12\x42\n\x06quests\x18\x05 \x01(\x0b\x32\x30.pogoprotos.data.quests.QuestPrecondition.QuestsH\x00\x1a$\n\x06Quests\x12\x1a\n\x12quest_template_ids\x18\x01 \x03(\t\x1a\\\n\x05Level\x12\x44\n\x08operator\x18\x01 \x01(\x0e\x32\x32.pogoprotos.data.quests.QuestPrecondition.Operator\x12\r\n\x05level\x18\x02 \x01(\x05\x1a\x8c\x01\n\x05Medal\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.BadgeType\x12\x44\n\x08operator\x18\x02 \x01(\x0e\x32\x32.pogoprotos.data.quests.QuestPrecondition.Operator\x12\x12\n\nbadge_rank\x18\x03 \x01(\x05\"B\n\x08Operator\x12\t\n\x05UNSET\x10\x00\x12\n\n\x06\x45QUALS\x10\x01\x12\x10\n\x0cGREATER_THAN\x10\x02\x12\r\n\tLESS_THAN\x10\x03\"\xa9\x02\n\x15QuestPreconditionType\x12\x1c\n\x18QUEST_PRECONDITION_UNSET\x10\x00\x12\x1c\n\x18QUEST_PRECONDITION_QUEST\x10\x01\x12\x1c\n\x18QUEST_PRECONDITION_LEVEL\x10\x02\x12\x1c\n\x18QUEST_PRECONDITION_MEDAL\x10\x03\x12\x1f\n\x1bQUEST_PRECONDITION_IS_MINOR\x10\x04\x12\'\n#QUEST_PRECONDITION_EXCLUSIVE_QUESTS\x10\x05\x12\x1c\n\x18QUEST_PRECONDITION_NEVER\x10\x06\x12\x30\n,QUEST_PRECONDITION_RECEIVED_ANY_LISTED_QUEST\x10\x07\x42\x0b\n\tConditionb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_badge__type__pb2.DESCRIPTOR,])



_QUESTPRECONDITION_OPERATOR = _descriptor.EnumDescriptor(
  name='Operator',
  full_name='pogoprotos.data.quests.QuestPrecondition.Operator',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUALS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREATER_THAN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LESS_THAN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=715,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_QUESTPRECONDITION_OPERATOR)

_QUESTPRECONDITION_QUESTPRECONDITIONTYPE = _descriptor.EnumDescriptor(
  name='QuestPreconditionType',
  full_name='pogoprotos.data.quests.QuestPrecondition.QuestPreconditionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_QUEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_LEVEL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_MEDAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_IS_MINOR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_EXCLUSIVE_QUESTS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_NEVER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEST_PRECONDITION_RECEIVED_ANY_LISTED_QUEST', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=784,
  serialized_end=1081,
)
_sym_db.RegisterEnumDescriptor(_QUESTPRECONDITION_QUESTPRECONDITIONTYPE)


_QUESTPRECONDITION_QUESTS = _descriptor.Descriptor(
  name='Quests',
  full_name='pogoprotos.data.quests.QuestPrecondition.Quests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quest_template_ids', full_name='pogoprotos.data.quests.QuestPrecondition.Quests.quest_template_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=476,
)

_QUESTPRECONDITION_LEVEL = _descriptor.Descriptor(
  name='Level',
  full_name='pogoprotos.data.quests.QuestPrecondition.Level',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='pogoprotos.data.quests.QuestPrecondition.Level.operator', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='pogoprotos.data.quests.QuestPrecondition.Level.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=570,
)

_QUESTPRECONDITION_MEDAL = _descriptor.Descriptor(
  name='Medal',
  full_name='pogoprotos.data.quests.QuestPrecondition.Medal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pogoprotos.data.quests.QuestPrecondition.Medal.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='pogoprotos.data.quests.QuestPrecondition.Medal.operator', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='badge_rank', full_name='pogoprotos.data.quests.QuestPrecondition.Medal.badge_rank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=713,
)

_QUESTPRECONDITION = _descriptor.Descriptor(
  name='QuestPrecondition',
  full_name='pogoprotos.data.quests.QuestPrecondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pogoprotos.data.quests.QuestPrecondition.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quest_template_id', full_name='pogoprotos.data.quests.QuestPrecondition.quest_template_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='pogoprotos.data.quests.QuestPrecondition.level', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='medal', full_name='pogoprotos.data.quests.QuestPrecondition.medal', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quests', full_name='pogoprotos.data.quests.QuestPrecondition.quests', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUESTPRECONDITION_QUESTS, _QUESTPRECONDITION_LEVEL, _QUESTPRECONDITION_MEDAL, ],
  enum_types=[
    _QUESTPRECONDITION_OPERATOR,
    _QUESTPRECONDITION_QUESTPRECONDITIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Condition', full_name='pogoprotos.data.quests.QuestPrecondition.Condition',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=111,
  serialized_end=1094,
)

_QUESTPRECONDITION_QUESTS.containing_type = _QUESTPRECONDITION
_QUESTPRECONDITION_LEVEL.fields_by_name['operator'].enum_type = _QUESTPRECONDITION_OPERATOR
_QUESTPRECONDITION_LEVEL.containing_type = _QUESTPRECONDITION
_QUESTPRECONDITION_MEDAL.fields_by_name['type'].enum_type = pogoprotos_dot_enums_dot_badge__type__pb2._BADGETYPE
_QUESTPRECONDITION_MEDAL.fields_by_name['operator'].enum_type = _QUESTPRECONDITION_OPERATOR
_QUESTPRECONDITION_MEDAL.containing_type = _QUESTPRECONDITION
_QUESTPRECONDITION.fields_by_name['type'].enum_type = _QUESTPRECONDITION_QUESTPRECONDITIONTYPE
_QUESTPRECONDITION.fields_by_name['level'].message_type = _QUESTPRECONDITION_LEVEL
_QUESTPRECONDITION.fields_by_name['medal'].message_type = _QUESTPRECONDITION_MEDAL
_QUESTPRECONDITION.fields_by_name['quests'].message_type = _QUESTPRECONDITION_QUESTS
_QUESTPRECONDITION_OPERATOR.containing_type = _QUESTPRECONDITION
_QUESTPRECONDITION_QUESTPRECONDITIONTYPE.containing_type = _QUESTPRECONDITION
_QUESTPRECONDITION.oneofs_by_name['Condition'].fields.append(
  _QUESTPRECONDITION.fields_by_name['quest_template_id'])
_QUESTPRECONDITION.fields_by_name['quest_template_id'].containing_oneof = _QUESTPRECONDITION.oneofs_by_name['Condition']
_QUESTPRECONDITION.oneofs_by_name['Condition'].fields.append(
  _QUESTPRECONDITION.fields_by_name['level'])
_QUESTPRECONDITION.fields_by_name['level'].containing_oneof = _QUESTPRECONDITION.oneofs_by_name['Condition']
_QUESTPRECONDITION.oneofs_by_name['Condition'].fields.append(
  _QUESTPRECONDITION.fields_by_name['medal'])
_QUESTPRECONDITION.fields_by_name['medal'].containing_oneof = _QUESTPRECONDITION.oneofs_by_name['Condition']
_QUESTPRECONDITION.oneofs_by_name['Condition'].fields.append(
  _QUESTPRECONDITION.fields_by_name['quests'])
_QUESTPRECONDITION.fields_by_name['quests'].containing_oneof = _QUESTPRECONDITION.oneofs_by_name['Condition']
DESCRIPTOR.message_types_by_name['QuestPrecondition'] = _QUESTPRECONDITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuestPrecondition = _reflection.GeneratedProtocolMessageType('QuestPrecondition', (_message.Message,), dict(

  Quests = _reflection.GeneratedProtocolMessageType('Quests', (_message.Message,), dict(
    DESCRIPTOR = _QUESTPRECONDITION_QUESTS,
    __module__ = 'pogoprotos.data.quests.quest_precondition_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestPrecondition.Quests)
    ))
  ,

  Level = _reflection.GeneratedProtocolMessageType('Level', (_message.Message,), dict(
    DESCRIPTOR = _QUESTPRECONDITION_LEVEL,
    __module__ = 'pogoprotos.data.quests.quest_precondition_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestPrecondition.Level)
    ))
  ,

  Medal = _reflection.GeneratedProtocolMessageType('Medal', (_message.Message,), dict(
    DESCRIPTOR = _QUESTPRECONDITION_MEDAL,
    __module__ = 'pogoprotos.data.quests.quest_precondition_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestPrecondition.Medal)
    ))
  ,
  DESCRIPTOR = _QUESTPRECONDITION,
  __module__ = 'pogoprotos.data.quests.quest_precondition_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestPrecondition)
  ))
_sym_db.RegisterMessage(QuestPrecondition)
_sym_db.RegisterMessage(QuestPrecondition.Quests)
_sym_db.RegisterMessage(QuestPrecondition.Level)
_sym_db.RegisterMessage(QuestPrecondition.Medal)


# @@protoc_insertion_point(module_scope)
