# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/ditto/rpc_response_event_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/ditto/rpc_response_event_params.proto',
  package='pogoprotos.data.ditto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5pogoprotos/data/ditto/rpc_response_event_params.proto\x12\x15pogoprotos.data.ditto\"J\n\x16RpcResponseEventParams\x12\x0e\n\x06rpc_id\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x10\n\x08payloads\x18\x03 \x03(\x0c\x62\x06proto3')
)




_RPCRESPONSEEVENTPARAMS = _descriptor.Descriptor(
  name='RpcResponseEventParams',
  full_name='pogoprotos.data.ditto.RpcResponseEventParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='pogoprotos.data.ditto.RpcResponseEventParams.rpc_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.data.ditto.RpcResponseEventParams.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payloads', full_name='pogoprotos.data.ditto.RpcResponseEventParams.payloads', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['RpcResponseEventParams'] = _RPCRESPONSEEVENTPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcResponseEventParams = _reflection.GeneratedProtocolMessageType('RpcResponseEventParams', (_message.Message,), dict(
  DESCRIPTOR = _RPCRESPONSEEVENTPARAMS,
  __module__ = 'pogoprotos.data.ditto.rpc_response_event_params_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.ditto.RpcResponseEventParams)
  ))
_sym_db.RegisterMessage(RpcResponseEventParams)


# @@protoc_insertion_point(module_scope)
