# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/titan/responses/get_available_submissions_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/titan/responses/get_available_submissions_response.proto',
  package='pogoprotos.networking.titan.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nNpogoprotos/networking/titan/responses/get_available_submissions_response.proto\x12%pogoprotos.networking.titan.responses\"\xdc\x01\n\x1fGetAvailableSubmissionsResponse\x12\x18\n\x10submissions_left\x18\x01 \x01(\x05\x12\x18\n\x10min_player_level\x18\x02 \x01(\x05\x12\x17\n\x0fhas_valid_email\x18\x03 \x01(\x08\x12\x1a\n\x12is_feature_enabled\x18\x04 \x01(\x08\x12,\n$time_window_for_submissions_limit_ms\x18\x05 \x01(\x03\x12\"\n\x1amax_poi_distance_in_meters\x18\x06 \x01(\x05\x62\x06proto3')
)




_GETAVAILABLESUBMISSIONSRESPONSE = _descriptor.Descriptor(
  name='GetAvailableSubmissionsResponse',
  full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='submissions_left', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.submissions_left', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_player_level', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.min_player_level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_valid_email', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.has_valid_email', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_feature_enabled', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.is_feature_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_window_for_submissions_limit_ms', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.time_window_for_submissions_limit_ms', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_poi_distance_in_meters', full_name='pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse.max_poi_distance_in_meters', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=342,
)

DESCRIPTOR.message_types_by_name['GetAvailableSubmissionsResponse'] = _GETAVAILABLESUBMISSIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAvailableSubmissionsResponse = _reflection.GeneratedProtocolMessageType('GetAvailableSubmissionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETAVAILABLESUBMISSIONSRESPONSE,
  __module__ = 'pogoprotos.networking.titan.responses.get_available_submissions_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.titan.responses.GetAvailableSubmissionsResponse)
  ))
_sym_db.RegisterMessage(GetAvailableSubmissionsResponse)


# @@protoc_insertion_point(module_scope)
