# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/ar_photo_session.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/ar_photo_session.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n0pogoprotos/data/telemetry/ar_photo_session.proto\x12\x19pogoprotos.data.telemetry\"\x90\x03\n\x0e\x41rPhotoSession\x12\x41\n\x07\x61r_type\x18\x01 \x01(\x0e\x32\x30.pogoprotos.data.telemetry.ArPhotoSession.ArType\x12O\n\x17\x66urthest_step_completed\x18\x02 \x01(\x0e\x32..pogoprotos.data.telemetry.ArPhotoSession.Step\x12\x18\n\x10num_photos_taken\x18\x03 \x01(\x05\x12\x19\n\x11num_photos_shared\x18\x04 \x01(\x05\"*\n\x06\x41rType\x12\t\n\x05UNSET\x10\x00\x12\x08\n\x04PLUS\x10\x01\x12\x0b\n\x07\x43LASSIC\x10\x02\"\x88\x01\n\x04Step\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1d\n\x19\x43\x41MERA_PERMISSION_GRANTED\x10\x01\x12\x16\n\x12\x41RPLUS_PLANE_FOUND\x10\x02\x12\x19\n\x15\x41RPLUS_POKEMON_PLACED\x10\x03\x12\x0f\n\x0bPHOTO_TAKEN\x10\x04\x12\x10\n\x0cPHOTO_SHARED\x10\x05\x62\x06proto3')
)



_ARPHOTOSESSION_ARTYPE = _descriptor.EnumDescriptor(
  name='ArType',
  full_name='pogoprotos.data.telemetry.ArPhotoSession.ArType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLUS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASSIC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=299,
  serialized_end=341,
)
_sym_db.RegisterEnumDescriptor(_ARPHOTOSESSION_ARTYPE)

_ARPHOTOSESSION_STEP = _descriptor.EnumDescriptor(
  name='Step',
  full_name='pogoprotos.data.telemetry.ArPhotoSession.Step',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_PERMISSION_GRANTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARPLUS_PLANE_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARPLUS_POKEMON_PLACED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHOTO_TAKEN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHOTO_SHARED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=344,
  serialized_end=480,
)
_sym_db.RegisterEnumDescriptor(_ARPHOTOSESSION_STEP)


_ARPHOTOSESSION = _descriptor.Descriptor(
  name='ArPhotoSession',
  full_name='pogoprotos.data.telemetry.ArPhotoSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ar_type', full_name='pogoprotos.data.telemetry.ArPhotoSession.ar_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='furthest_step_completed', full_name='pogoprotos.data.telemetry.ArPhotoSession.furthest_step_completed', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_photos_taken', full_name='pogoprotos.data.telemetry.ArPhotoSession.num_photos_taken', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_photos_shared', full_name='pogoprotos.data.telemetry.ArPhotoSession.num_photos_shared', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARPHOTOSESSION_ARTYPE,
    _ARPHOTOSESSION_STEP,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=480,
)

_ARPHOTOSESSION.fields_by_name['ar_type'].enum_type = _ARPHOTOSESSION_ARTYPE
_ARPHOTOSESSION.fields_by_name['furthest_step_completed'].enum_type = _ARPHOTOSESSION_STEP
_ARPHOTOSESSION_ARTYPE.containing_type = _ARPHOTOSESSION
_ARPHOTOSESSION_STEP.containing_type = _ARPHOTOSESSION
DESCRIPTOR.message_types_by_name['ArPhotoSession'] = _ARPHOTOSESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArPhotoSession = _reflection.GeneratedProtocolMessageType('ArPhotoSession', (_message.Message,), dict(
  DESCRIPTOR = _ARPHOTOSESSION,
  __module__ = 'pogoprotos.data.telemetry.ar_photo_session_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.ArPhotoSession)
  ))
_sym_db.RegisterMessage(ArPhotoSession)


# @@protoc_insertion_point(module_scope)
