# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/social_player_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/player/social_player_settings.proto',
  package='pogoprotos.data.player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3pogoprotos/data/player/social_player_settings.proto\x12\x16pogoprotos.data.player\";\n\x14SocialPlayerSettings\x12#\n\x1b\x64isable_last_pokemon_caught\x18\x01 \x01(\x08\x62\x06proto3')
)




_SOCIALPLAYERSETTINGS = _descriptor.Descriptor(
  name='SocialPlayerSettings',
  full_name='pogoprotos.data.player.SocialPlayerSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='disable_last_pokemon_caught', full_name='pogoprotos.data.player.SocialPlayerSettings.disable_last_pokemon_caught', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['SocialPlayerSettings'] = _SOCIALPLAYERSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocialPlayerSettings = _reflection.GeneratedProtocolMessageType('SocialPlayerSettings', (_message.Message,), dict(
  DESCRIPTOR = _SOCIALPLAYERSETTINGS,
  __module__ = 'pogoprotos.data.player.social_player_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.player.SocialPlayerSettings)
  ))
_sym_db.RegisterMessage(SocialPlayerSettings)


# @@protoc_insertion_point(module_scope)
